author: yanm1ng # 作者
description: yanm1ng's blog
keyword: hexo-theme, vuejs

excerpt_link: Read more

menu:
 Home: /
 Series: /series/
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set utterances, gitment, uyan or disqus
comment: utterances
# Gitment
utterances_repo: mike-box/blogtalk
utterances_issue_term: "pathname"
utterances_theme: github-light

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics: 
# disqus config
disqus_shortname: 

about: 
  banner: ""
  avatar: https://raw.githubusercontent.com/mike-box/pic/main/202211022243266.webp
  description: "god bless you."
  github_username: mike-box
  zhihu_username: da-hua-niu
  linkedin_username: mingliang meng

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true

# China Registration
# e.g. 京ICP备12345678号-1
icp:
  enable: false
  number: 京ICP备12345678号-1 # e.g. 京ICP备12345678号-1
# e.g. 京公网安备 12345678901234号
ga:
  enable: false
  province: 京           # e.g. 京
  number: 12345678901234 # e.g. 12345678901234

